### ISSUE TITLE
What extra advantage of using bloomer instead of plain bulma css classes

### ISSUE THREAD

**Issue by lokesh1729** [AlgusDark/bloomer#136]
Hi,

I am wondering what extra advantages does bloomer provide than using plain bulma css classes.

If we are using plain bulma, we will import whole css (`@import bulma/bulma.css`), so there we have unused css classes, so the css bundle size would be high. When using bloomer components, if I am importing a component (say button component), will it only include css for that component ?? thereby reducing the size of css bundle ?

**Comment by AlgusDark** [comment]
Hi,
bloomer are just react bindings... it doesn't export `bulma`, you need to do that.

So, the only advantage of using plain css clases is that you have react bindings so you don't need to write them.

At first, I wanted to create the thing you mention on export only some parts, but wanted to do it with styled-components or other CSS-in-js... problem is that is an entire rewrite and will be hard to maintain. 

But, for what you want, you can use something like _purgecss_.

**Comment by lokesh1729** [comment]
Hi,

thanks for quick revert, i really appreciate. rewriting with `css-in-js` is very hard... i got answer to my question. hence closing the issue :)

**Comment by lokesh1729** [comment]
@AlgusDark : I used bloomer in one of my projects, the problem is that, i need to refer both bulma and bloomer documentation to write code, also when using bloomer, it's hard to figure out whether a particular component is block level or inline or inline-block HTML element.

**Comment by AlgusDark** [comment]
I see... yes, I need to rewrite this but since I moved to Japan, surprisingly I haven't found any free time.

I believe that there is no easy way to figure out the `display` of a react component in any UI library.

Anyhow, if you find some ideas, I would appreciate. Maybe it's better to have a V2 with Bulma inside and have a webpack loader to remove some CSS that isn't needed (with the help of _purgecss_?)
