### ISSUE TITLE
New API for Columns

### ISSUE THREAD

**Issue by AlgusDark** [AlgusDark/bloomer#48]
| Prop | Description |
| --- | --- |
|*isSize* | `1..12` - `'3/4'` - `'2/3'` - `'1/2'` - `'1/3'` - `'1/4'` - `'full'` - `'narrow'` |
|*isMobile*| same as above |
|*isTablet*| same as above |
|*isDesktop*| same as above |

That way we can remove props `isFull`, `isNarrow`, `isThreeQuarters`, `isTwoThirds`, `isHalf`, `isOneThird`, `isOneQuarter`.

The same should occur to *Offset* props, leaving only `isOffset`, `isOffsetMobile`, `isOffsetTablet`, `isOffsetDesktop`.

That would be a total of `12` props removed.

**Important:** *Offset* doesn't have `full` or `narrow`, but it has the other sizes.

**Comment by AlgusDark** [comment]
After that, we can leave it to only two props:

| Prop | type |
| --- | --- |
| isSize | `number` - `string` - `object` |
| isOffset | same as above |

so users can do something like:
```javascript
const size = {
  mobile: '1/2',
  tablet: 'full'
  desktop: '3',
}

const offset = {
  mobile: '3',
  desktop: 6
}

<Column isSize={size} isOffset={offset} > My Column </Column>
```

**rendering:**
```html
<div
  class='is-half-mobile
    is-full-tablet
    is-3-desktop
    is-offset-3-mobile
    is-offset-6-desktop'>
  My Column
</div>
```

Leaving that to only two props to use.

Also, this way we can introduce `widescreen` modifier, since I forgot to include that (but is already in the code).

**Comment by shubhranshu** [comment]
What is the process for updating the website. **Footer** example still have a **isFull** prop being injected. There is a similar issues with **Nav** example.
