### ISSUE TITLE
Not applying 'is-fullwidth' to button

### ISSUE THREAD

**Issue by venomlust** [AlgusDark/bloomer#75]
`is-fullwidth` css rule is not applying for the button when using `isFullWidth={true}`

**Comment by omganunicorn** [comment]
This is working for me; since isFullWidth is part of the helpers, adding either the `isFullWidth` prop or making it dynamic with `isFullWidth={true}` worked.

**Comment by AlgusDark** [comment]
Button (as all bloomer elements/components) has all the helpers props as you can see at [Button.tsx](https://github.com/AlgusDark/bloomer/blob/master/src/elements/Button.tsx#L55).

`<Button isFullWidth/>` or `<Button isFullWidth={true}/>` works fine.

Closing this issue, you can open it if you found that something is wrong.
