### ISSUE TITLE
Missing hasTextAlign on Container component

### ISSUE THREAD

**Issue by venomlust** [AlgusDark/bloomer#77]
Missing `hasTextAlign` on Container component

**Comment by AlgusDark** [comment]
`Container` (as all bloomer elements/components) has all the [helpers props](https://bloomer.js.org/#/documentation/overview/helpers) as you can see at [Container.tsx](https://github.com/AlgusDark/bloomer/blob/master/src/layout/Container.tsx#L24).

`<Container hasTextAlign="centered"/>` works fine.

Can you confirm and close the issue if everything is ok?

Thanks!
