### ISSUE TITLE
Some more complex components?

### ISSUE THREAD

**Issue by atrauzzi** [AlgusDark/bloomer#95]
Looking at Buefy and it seems to have quite a few interesting and useful components implemented.

- https://buefy.github.io/#/documentation/datepicker
- https://buefy.github.io/#/documentation/taginput
- https://buefy.github.io/#/documentation/timepicker
- https://buefy.github.io/#/documentation/upload

Any chance you'll be including some as part of bloomer as well?

**Comment by AlgusDark** [comment]
Hi, it seems that maybe we can do something in V1, once that we pass everything to Styled-Components. Once that's complete, maybe we can start with some of these nice looking components.

I'll close it since this is going to be in a milestone.

Thanks!
